### ISSUE TITLE
Keyboard shortcut not working

### ISSUE THREAD

**Issue by arorarajan** [timbru31/quickjira#1]
I'm on OS X 10.10.2 running latest version of Chrome and the keyboard shortcut doesn't work for me. I have tried both Control + shift + L and Command + Shift + L to no avail.
Any other setting I can try changing? I checked for my OS X keyboard shortcuts and that shortcut isn't being used by another app from what I can tell.

**Comment by timbru31** [comment]
Hi,

thanks for the report, I can confirm this issue. I'm not sure why the shortcut is not working. Chrome does not register the shortcut if there is another app using the same shortcut. Since there seems no other conflicting app, you can set the shortcut manually:

Chrome settings --> Settings --> Extensions --> scroll down, on the right bottom you can see "shortcuts" --> define CMD + SHIFT + L for quickjira (or any other one you want to use)

Let me know if this workaround worked for you.

**Comment by rajan-ad** [comment]
Hi,

Thanks for the quick response. That workaround worked just fine and I can hit Command+Shift+L now to bring up the extension window. I see you changed the shortcut too, hopefully that helps other folks.

Cheers!

**Comment by arorarajan** [comment]
Hi,

Thanks for the quick response. That workaround worked just fine and I can hit Command+Shift+L now to bring up the extension window. I see you changed the shortcut too, hopefully that helps other folks.

Cheers!

**Comment by timbru31** [comment]
Great.

Yes, I quickly tested the new shortcut on OS X, Win and Ubuntu, worked out of the box on all three.
Still strange why the old shortcut did not work..

**Comment by cliss1974** [comment]
@timbru31 Hi Tim.  I have been having this shortcut issue on Mac 10.14 and chrome 71.   Any thoughts on a workaround?  I don't see a way to change the shortcuts in the most recent version 0.11.0
